---
name: PremiumCase
author: J0k3rrWild
version: 1.4.2
main: J0k3rrWild\PremiumCase\Main
api: 3.25.1
website: https://github.com/J0k3rrWild
commands:
 pandorka:
<<<<<<< HEAD
  description: PremiumCase main command
  permission: premiumcase.command.premiumcase
  usage: /pc giveall <amount> | give <amount> <player>| reload
  aliases: ["pc", "premiumcase"]
permissions:
  premiumcase:
    default: op
    description: Gives permission to all premium case commands 
  premiumcase.reload:
    default: op
    description: Gives permission to reload premium case configurations
  premiumcase.give:
    default: op
    description: Gives you the power to give premium case
=======
  description: Główna komenda pandorek
  permission: pandorka.command.pandorka
  usage: /pandorka giveall/give <amount> | reload
  aliases: [pandorka, pd, pc, premiumcase]
permissions:
  premiumcase:
    default: op
    description: Daje uprawnienia do wszystkich komend pandorki
    children:
      premiumcase.reload:
        default: op
        description: Daje uprawnienia do przeładowania konfiguracji pandorek
        children:
         premiumcase.give:
         default: op
         description: Daje uprawnienia do dawania pandorek
>>>>>>> 4328da2222e042ccf3459c219afbe7916a5d0fd4
...
