---
name: PremiumCase
author: J0k3rrWild
version: 1.4.2
main: J0k3rrWild\PremiumCase\Main
api: 4.0.3
website: https://github.com/J0k3rrWild
permissions:
  premiumcase:
    default: op
    description: Daje uprawnienia do wszystkich komend pandorki
  premiumcase.reload:
    default: op
    description: Daje uprawnienia do przeładowania konfiguracji pandorek
  premiumcase.give:
    default: op
    description: Daje uprawnienia do dawania pandorek
...
