---
name: PremiumCase
author: J0k3rrWild
version: 1.4.2
main: J0k3rrWild\PremiumCase\Main
api: 4.0.0
website: https://github.com/J0k3rrWild
permissions:
  premiumcase:
    default: op
    description: Gives permission to all premium case commands 
  premiumcase.reload:
    default: op
    description: Gives permission to reload premium case configurations
  premiumcase.give:
    default: op
    description: Gives you the power to give premium case
...
